### ISSUE TITLE
FileDelete On writeResultsToFile

### ISSUE THREAD

**Issue by JMPSequeira** [Chunjee/expect.ahk#2]
I was wondering if it would append to conout and passed and passed the *, as per AHK documentation, and it erased my project. 

I think this should be an opt in and not a default behavior.

**Comment by Chunjee** [comment]
I'm very sorry about the issue you encountered. I don't like having `fileDelete` in the code at all! I will try an idea to defensively prevent that kind of problem but if you have a better idea please let me know
